const test=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js');
const now='2026-10-05T00:00:00.000Z';
const record=(changes={})=>({id:'r1',title:'文字数',content:'1200字',scope:'全体',kind:'constraint',status:'active',author:'user',approved:true,source:'source',createdAt:now,updatedAt:now,supersedes:null,history:[],...changes});
const project=(records=[])=>({id:'p1',name:'記事',goal:'goal',next:'next',records});
const store=(p=project())=>({app:'tsuzuki-kara',version:1,activeProject:'p1',projects:[p]});
test('empty project validates',()=>assert.deepEqual(C.validateStore(store()),store()));
test('unapproved active record rejected',()=>assert.throws(()=>C.validateRecord(record({approved:false}))));
test('pending AI record accepted',()=>assert.equal(C.validateRecord(record({author:'ai',status:'pending',approved:false})).status,'pending'));
test('unknown state rejected',()=>assert.throws(()=>C.validateRecord(record({status:'whatever'}))));
test('empty title rejected',()=>assert.throws(()=>C.validateRecord(record({title:' '}))));
test('invalid timestamps rejected',()=>assert.throws(()=>C.validateRecord(record({createdAt:'bad'}))));
test('add creates independent copy',()=>{const p=project(),r=record();C.addRecord(p,r);r.content='mutated';assert.equal(p.records[0].content,'1200字');});
test('same key active record conflicts',()=>{const p=project([record()]);assert.equal(C.conflicts(p,record({id:'r2'})).length,1);});
test('different scope does not conflict',()=>{const p=project([record()]);assert.equal(C.conflicts(p,record({id:'r2',scope:'記事A'})).length,0);});
test('NFKC title and case normalization',()=>{const p=project([record({title:'ＡＢＣ'})]);assert.equal(C.conflicts(p,record({id:'r2',title:'abc'})).length,1);});
test('unconfirmed replacement throws without mutation',()=>{const p=project([record()]);assert.throws(()=>C.addRecord(p,record({id:'r2'})));assert.equal(p.records[0].status,'active');assert.equal(p.records.length,1);});
test('approved replacement marks old as superseded',()=>{const p=project([record()]);C.addRecord(p,record({id:'r2',content:'800字'}),true,now);assert.equal(p.records[0].status,'superseded');assert.equal(p.records[1].supersedes,'r1');assert.equal(C.activeForScope(p,'全体')[0].content,'800字');});
test('pending replacement leaves original active',()=>{const p=project([record()]);C.addRecord(p,record({id:'r2',content:'800字',status:'pending',approved:false,supersedes:'r1'}));assert.equal(p.records[0].status,'active');});
test('approval of pending replacement supersedes old',()=>{const p=project([record(),record({id:'r2',status:'pending',approved:false,supersedes:'r1'})]);C.transition(p,'r2','active',true,now);assert.equal(p.records[0].status,'superseded');assert.equal(p.records[1].approved,true);});
test('rejection does not activate a proposal',()=>{const p=project([record({status:'pending',approved:false})]);C.transition(p,'r1','rejected');assert.equal(C.activeForScope(p,'全体').length,0);});
test('archive and restore returns to pending, not active',()=>{const p=project([record()]);C.transition(p,'r1','archived');C.transition(p,'r1','pending');assert.equal(p.records[0].approved,false);});
test('reapproving a former ancestor does not create history cycle',()=>{const p=project([record()]);C.addRecord(p,record({id:'r2'}),true);C.transition(p,'r1','archived');C.transition(p,'r1','pending');C.transition(p,'r1','active',true);assert.doesNotThrow(()=>C.validateStore(store(p)));});
test('global export excludes task-specific records',()=>{const p=project([record(),record({id:'r2',scope:'記事A',content:'800字'})]);assert.equal(C.activeForScope(p,'全体').length,1);assert.equal(C.activeForScope(p,'全体')[0].content,'1200字');});
test('task scope overrides same-title global rule',()=>{const p=project([record(),record({id:'r2',scope:'記事A',content:'800字'})]);assert.deepEqual(C.activeForScope(p,'記事A').map(r=>r.content),['800字']);});
test('global unrelated conditions still included',()=>{const p=project([record({title:'文体'}),record({id:'r2',scope:'記事A'})]);assert.equal(C.activeForScope(p,'記事A').length,2);});
test('other scopes never leak into export',()=>{const p=project([record({scope:'記事A',content:'SECRET A'})]);assert.ok(!C.buildHandoff(p,'記事B').includes('SECRET A'));});
test('superseded rules excluded by default',()=>{const p=project([record({status:'superseded',content:'OLD-2000'}),record({id:'r2',content:'NEW-1200'})]);const out=C.buildHandoff(p);assert.ok(out.includes('NEW-1200'));assert.ok(!out.includes('OLD-2000'));});
test('pending proposals excluded by default',()=>assert.ok(!C.buildHandoff(project([record({status:'pending',approved:false,content:'PENDING'} )])).includes('PENDING')));
test('pending proposals included in a separated section only',()=>{const out=C.buildHandoff(project([record({status:'pending',approved:false,content:'PENDING'})]),'全体',{pending:true});assert.ok(out.indexOf('PENDING')>out.indexOf('未承認の提案（実行指示ではない）'));});
test('history only when explicitly enabled',()=>{const out=C.buildHandoff(project([record({status:'superseded',content:'OLD'})]),'全体',{history:true});assert.ok(out.indexOf('OLD')>out.indexOf('過去の記録（現在は無効'));});
test('source content optional',()=>{assert.ok(!C.buildHandoff(project([record()])).includes('source'));assert.ok(C.buildHandoff(project([record()]),'全体',{sources:true}).includes('source'));});
test('rejected can be excluded',()=>assert.ok(!C.buildHandoff(project([record({status:'rejected',content:'REJECTED'})]),'全体',{rejected:false}).includes('REJECTED')));
test('completed next actions excluded from active',()=>assert.equal(C.activeForScope(project([record({kind:'next',status:'done'})]),'全体').length,0));
test('duplicate active records rejected on import',()=>assert.throws(()=>C.validateStore(store(project([record(),record({id:'r2'})])))));
test('duplicate IDs rejected on import',()=>assert.throws(()=>C.validateStore(store(project([record(),record({status:'pending',approved:false})])))));
test('dangling history reference rejected',()=>assert.throws(()=>C.validateStore(store(project([record({supersedes:'missing'})])))));
test('cyclic history rejected',()=>assert.throws(()=>C.validateStore(store(project([record({supersedes:'r2'}),record({id:'r2',status:'superseded',supersedes:'r1'})])))));
test('missing selected project falls back to first project',()=>assert.equal(C.validateStore({...store(),activeProject:'missing'}).activeProject,'p1'));
test('invalid version rejected',()=>assert.throws(()=>C.validateStore({...store(),version:99})));
test('Markdown control characters escaped',()=>assert.ok(C.buildHandoff(project([record({title:'<img onerror=x>',content:'**text**'})])).includes('\\<img onerror=x\\>')));
